### ISSUE TITLE
400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/

### ISSUE THREAD

**Issue by diegovargasf** [jmfernandes/robin_stocks#25] opened 2019-05-02 04:48 UTC
I have encountered this issue today:
```
 token = 'Bearer {}'.format(data['access_token'])
TypeError: 'NoneType' object is not subscriptable

```
I have done some digging and it looks like the issue is happening in this line in authetication.py:
`data = helper.request_post(url,payload)`

The error that I'm seeing is:
`data = helper.request_post(url,payload)`

this is the redacted payload, note that the password and username are working correctly in the robinhood app.

```
challenge_type:sms
client_id:xxx
device_token:b34e3cf0-c549-8cef-2722-4f662bb12d96
expires_in:86400
grant_type:password
password:xxx
scope:internal
username:diego.vargas.frontanilla@xxx

```
I've seen this error before but it usually went away after restarting my python interpreter, however today, it is just not going away. I have even tried re installing robin_stocks.

**Comment by dirigible37** [comment] 2019-05-05 17:05
Although I don't have 2FA setup, it seems I get a text message with a 6 digit code when I call .login() and receive this 400 error. So I am assuming it's something having to do with that.

**Comment by shubhamgandhi** [comment] 2019-05-08 17:07
Same issue here. Something seems to have changed on Robinhood's end?

**Comment by shubhamgandhi** [comment] 2019-05-08 17:08
> Although I don't have 2FA setup, it seems I get a text message with a 6 digit code when I call .login() and receive this 400 error. So I am assuming it's something having to do with that.

Yep, I got the same thing. Only once though, out of many login attempts.

**Comment by fanliangdong** [comment] 2019-06-18 21:30
Having the same issue, not sure what is going on, any solutions?

**Comment by celmore25** [comment] 2019-07-02 18:34
Same problem. Does anyone know what the "res.raise_for_status()" line is doing inside of help.request_port? That is where I am getting my error message.

**Comment by Scr44gr** [comment] 2019-07-23 19:33
The problem is that the verification code that is sent via sms you can not put it in code, there is no method for that, I will write one and make a pull requests as soon as possible to solve this.

**Comment by Jmarkaba** [comment] 2019-08-07 02:00
Please see my comment on #24

**Comment by jmfernandes** [comment] 2019-08-08 16:12
closing. see issue #24

**Closed by jmfernandes** 2019-08-08 16:12 UTC
