### ISSUE TITLE
Authentication Timeout after 24hrs

### ISSUE THREAD

**Issue by jmyers350** [jmfernandes/robin_stocks#47] opened 2019-09-20 19:51 UTC
Was curious if someone had a workaround that would extend the Authentication almost indefinitely.  I apologize if this is a redundant or previously solved issue, I haven't found a direct answer to this question yet.

class online_collect():
    def login(self):
        username = 'xxxxxxx@hotmail.com'
        password = 'xxxxxxxxx'
        login = r.login(username,password, expiresIn = 3000000, by_sms = True, store_session = True)

Thanks

**Comment by jmyers350** [comment] 2019-10-01 02:37
I have a workaround for this, although I did not correct the issue, I have a way to make it not a burden.  I am not sure if anyone is watching this.

**Comment by jmyers350** [comment] 2019-10-01 03:44
For those that want to use what I made, all it does is said a telegram prompt and allows you to remotely solve the challenge by responding to the Telegram message in telegram.  To use this change, all you need to do is generate a telegram bot and retrieve the token from it.  The changes I made are all in authentication.py and are as follows:

#==========================================================================
import requests
import json
import time



def get_url(url):
    response = requests.get(url)
    content = response.content.decode("utf8")
    return content


def get_json_from_url(url):
    content = get_url(url)
    js = json.loads(content)
    return js


def get_updates(TOKEN):
    URL = "https://api.telegram.org/bot{}/".format(TOKEN)
    url = URL + "getUpdates"
    js = get_json_from_url(url)
    return js


def get_last_chat_id_and_text(updates):
    num_updates = len(updates["result"])
    last_update = num_updates - 1
    text = updates["result"][last_update]["message"]["text"]
    chat_id = updates["result"][last_update]["message"]["chat"]["id"]
    return (text, chat_id)


def custom(message, TOKEN):
    bot_message = message
    bot_token = TOKEN
    bot_chatID = '841481087'
    send_text = 'https://api.telegram.org/bot' + bot_token + '/sendMessage?chat_id=' + bot_chatID + '&parse_mode=Markdown&text=' + bot_message

    response = requests.get(send_text)

    return response.json()

#===========================================================================

def login(username,password,expiresIn=86400,scope='internal',by_sms=True,store_session=True,telegram=False):

elif 'challenge' in data:
        challenge_id = data['challenge']['id']

        print('Robinhood Challenge Sent to User')
        if telegram == False:
            sms_code = input('Enter Robinhood code for validation: ')

        #==================================================================
        else:
            custom('What is the Robin Authentication?', telegram)
            draw = (get_last_chat_id_and_text(get_updates(telegram)))
            old_message = draw[0]

            while True:
                draw = (get_last_chat_id_and_text(get_updates(telegram)))
                new_message = draw[0]
                x = 0
                if old_message == new_message:
                    x = x + 1
                    if x == 60:
                        print('Failed to Receive Message')
                        break
                    time.sleep(1)
                else:
                    print('Message Received')
                    print(new_message)
                    break
            sms_code = new_message
        #================================================================




        res = respond_to_challenge(challenge_id, sms_code)
        while 'challenge' in res and res['challenge']['remaining_attempts'] > 0:
            sms_code = input('That code was not correct. {0} tries remaining. Please type in another code: '.format(res['challenge']['remaining_attempts']))
            res = respond_to_challenge(challenge_id, sms_code)
        helper.update_session('X-ROBINHOOD-CHALLENGE-RESPONSE-ID', challenge_id)
        data = helper.request_post(url,payload)
    # Update Session data with authorization or raise exception with the information present in data.

**Comment by jmfernandes** [comment] 2020-03-11 20:44
closing because the robinhood api is working as intended.

**Closed by jmfernandes** 2020-03-11 20:44 UTC

**Comment by emberrett** [comment] 2022-04-21 17:55
There's actually a simple way to do this (from [here](https://robin-stocks.readthedocs.io/en/latest/quickstart.html). 

> [](https://robin-stocks.readthedocs.io/en/latest/quickstart.html#with-mfa-entered-programmatically-from-time-based-one-time-password-totp)With MFA entered programmatically from Time-based One-Time Password (TOTP)
NOTE: to use this feature, you will have to sign into your robinhood account and turn on two factor authentication. Robinhood will ask you which two factor authorization app you want to use. Select “other”. Robinhood will present you with an alphanumeric code. This code is what you will use for “My2factorAppHere” in the code below. Run the following code and put the resulting MFA code into the prompt on your robinhood app.

>>> import pyotp
>>> totp  = pyotp.TOTP("My2factorAppHere").now()
>>> print("Current OTP:", totp)

>Once you have entered the above MFA code (the totp variable that is printed out) into your Robinhood account, it will give you a backup code. Make sure you do not lose this code or you may be locked out of your account!!! You can also take the exact same “My2factorAppHere” from above and enter it into your phone’s authentication app, such as Google Authenticator. This will cause the exact same MFA code to be generated on your phone as well as your python code. This is important to do if you plan on being away from your computer and need to access your Robinhood account from your phone.

>Now you should be able to login with the following code:

>>> import pyotp
>>> import robin_stocks.robinhood as r
>>> totp  = pyotp.TOTP("My2factorAppHere").now()
>>> login = r.login('joshsmith@email.com','password', mfa_code=totp)

>Not all of the functions contained in the module need the user to be authenticated. A lot of the functions contained in the modules ‘stocks’ and ‘options’ do not require authentication, but it’s still good practice to log into Robinhood at the start of each script.
